ci:
  collect:
    numberOfRuns: 1
    staticDistDir: ./_site
    url:
      - http://localhost/
      - http://localhost/projects
      - http://localhost/funding/seed-grants
      - http://localhost/people
      - http://localhost/curriculum/courses
      - http://localhost/projects/brown/
  assert:
    assertions:
      categories:performance: off
      categories:pwa: off
  upload:
    target: temporary-public-storage
