---
title: DH@NYU
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  updates:
    title: Updates
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
email: youremailaddress@gmail.com
description: Digital Humanities at New York University
baseurl: ''
url: ''
permalink: pretty
logo-image-url: images/logo.png
github_username: ''
twitter_username: ''
markdown: kramdown
