---
title: DH@NYU
timezone: UTC
email: dh.help@nyu.edu
long_title: "Welcome to Digital Humanities at <br>New York University."
description: "Here you'll find sit amet, consectetur adipiscing elit. Sed eu elit in diam congue vehicula non sed magna. Aenean sit amet odio auctor, bibendum est eget, ultricies justo. Phasellus aliquam diam nec purus tincidunt lacinia. Duis eu porta enim, a fermentum eros. Phasellus placerat rutrum molestie."

baseurl: ''
url: 'https://nyu-dh.github.io'

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown
plugins:
  - pagemaster

collections:
  pages:
    title: Pages
    output: true
  updates:
    title: Updates
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
    layout: project
    source: projects.yml
    id_key: title

search:
  index: index.json
