title: 'New York University Digital Humanities'
short_title: 'NYU DH'
# tagline: >
#   The Digital Humanities Initiative at [University Name] aims to integrate technology with the study of humanities subjects, creating new methods for research, teaching, and preservation. Our interdisciplinary approach combines expertise in the humanities, computer science, and information technology to explore digital approaches to cultural heritage, text analysis, and multimedia projects. Through our research and educational programs, we strive to advance digital literacy and facilitate innovative collaborations between scholars, students, and cultural organizations.
tagline: >
  We focus on new technologies, advanced computing, and public engagement to inform and interrogate humanistic inquiry.
limerick: >
  Welcome to the NYU DH Periphery /
  Out here things are rather slippery /
  We have great Initiative and a Center of thought /
  Come join our NYU DH Mystery
timezone: UTC
email: dh.help@nyu.edu

semester:
  current: 'Spring 2023'
  next: 'Fall 2023'

url: 'https://digitalhumanities.nyu.edu'
baseurl: ''
future: true
show_footer: true
source: source
theme: nyu-dh-theme
plugins:
  - pagemaster
  - jekyll-seo-tag

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
google_analytics: 'G-R2JKDFQRDJ'


collections:
  news:
    output: true
  project_tags:
    output: true
    source: project_tags.yml
    id_key: slug
    layout: project-tag-page
    permalink: /projects/tag/:title/
  projects:
    output: true
    source: projects.yml
    id_key: pid
    layout: project

defaults:
  - scope:
      type: news
    values:
      layout: news

# seo
twitter:
  username: nyu_dh
