---
title: DH@NYU
timezone: UTC
email: dh.help@nyu.edu
description: Digital Humanities at New York University
baseurl: ''
url: ''
permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  updates:
    title: Updates
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
