title: 'NYU DH'
full_title: 'Digital Humanities<br>at New York University'
description: >
  NYU DH focuses on new technologies, advanced computing, and public engagement to inform and interrogate humanistic inquiry.
limerick: >
  Welcome to the NYU DH Periphery /
  Out here things are rather slippery /
  We have great Initiative and a Center of thought /
  Come join our NYU DH Mystery
timezone: UTC
email: dh.help@nyu.edu

semester:
  current: 'Spring 2022'
  next: 'Fall 2022'

url: ''
baseurl: ''
future: true
show_footer: true
source: source
theme: nyu-dh-theme
plugins:
  - pagemaster

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown

collections:
  news:
    output: true
  project_tags:
    output: true
    source: project_tags.yml
    id_key: slug
    layout: project-tag-page
    permalink: /projects/tag/:title
  projects:
    output: true
    source: projects.yml
    id_key: pid
    layout: project

defaults:
  - scope:
      type: news
    values:
      layout: news
