name: fetch data deploy prod
on: workflow_dispatch

jobs:
  prod-fetch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips libvips-dev
      - uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
      - name: get datetime
        run: echo "NOWISH=$(TZ=America/New_York date)" >> ${GITHUB_ENV}
      - name: install gems 
        run: bundle install
      - name: fetch data
        env:
          COURSES_SHEET_KEY: ${{secrets.COURSES_SHEET_KEY}}
          PEOPLE_SHEET_KEY: ${{secrets.PEOPLE_SHEET_KEY}}
          PROJECTS_SHEET_KEY: ${{secrets.PROJECTS_SHEET_KEY}}
        run: bundle exec rake fetch:all
      - name: test html
        run: bundle exec rake site:test
      - name: build site
        run: bundle exec jekyll build
      - name: ftp deploy to host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_PROD_SERVER}}
          username: ${{secrets.FTP_PROD_USER}}
          password: ${{secrets.FTP_PROD_PW}}
          protocol: ftps
          state-name: ./.ftp-deploy-sync-state.json
          local-dir: ./_site/

