name: prod fetch and deploy

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'Deploy message'
        required: true

jobs:
  prod-fetch-deploy:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # fetch data
      - run: bundle exec rake fetch:all
      # build
      - run: bundle exec rake site:build
      # test html
      - run: bundle exec rake site:test
      # deploy via ftp
      - uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: dh.hosting.nyu.edu
          username: ${{secrets.FTP_USERNAME}}@dh.hosting.nyu.edu
          password: ${{secrets.FTP_PASSWORD}}
          state-name: ./.ftp-deploy-sync-state.json
          local-dir: ./_site/
