name: prod deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'README.md'
      - '.github/workflows/test*.yml'

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
      - name: install gems 
        run: bundle install
      - name: test html
        run: bundle exec rake site:test
      - name: build site
        run: bundle exec jekyll build
      - name: gh-deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
          cname: digitalhumanities.nyu.edu
          
         
