name: prod deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'README.md'
      - '.github/workflows/test*.yml'

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # test html
      - name: test html
        run: bundle exec rake site:test
      # build site
      - name: build site
        run: bundle exec jekyll build
      # deploy via ftp
      - name: ftp deploy to host
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{secrets.FTP_PROD_SERVER}}
          username: ${{secrets.FTP_PROD_USER}}
          password: ${{secrets.FTP_PROD_PW}}
          protocol: ftps
          state-name: ./.ftp-deploy-sync-state.json
          local-dir: ./_site/
