name: stage deploy

on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'README.md'
      - '.github/workflows/test*.yml'

jobs:
  stage-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
      - name: install gems 
        run: bundle install
      - name: build site
        run: bundle exec jekyll build --config _config.yml,_staging.yml
      - name: block indexing
        run: 'mkdir -p _site && echo -e "User-agent: *\nDisallow: /\n" > _site/robots.txt'
      - name: ftp deploy to host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_STAGE_SERVER}}
          username: ${{secrets.FTP_STAGE_USER}}
          password: ${{secrets.FTP_STAGE_PW}}
          protocol: ftps
          state-name: ./.ftp-deploy-sync-state.json
          local-dir: ./_site/
