name: test
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'README.md'
      - '.github/workflows/wh-ftp-deploy.yml'
      - '.github/workflows/a11y.yml'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'README.md'
      - '.github/workflows/wh-ftp-deploy.yml'
      - '.github/workflows/a11y.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEURL: ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: install gems
        run: bundle install
      - name: build
        run: bundle exec rake site:build
      - name: test
        run: bundle exec rake site:test
