name: htmlproofer test
on:
  pull_request:
    branches:
      - main

jobs:
  test-html:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
      # test html + internal links
      - name: test html
        run: bundle exec rake site:test
      # test external links
      - name: test linkrot
        run:  bundle exec rake site:test:linkrot
