name: lighthouse a11y test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "NODE_VERSION=$(cat '.nvmrc')" >> ${GITHUB_ENV}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
      - name: install gems 
        run: bundle install
      - name: build site
        run: bundle exec jekyll build
      - name: test a11y
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun
