name: lighthouse a11y test
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'README.md'
      - '.github/workflows/*deploy.yml'
      - '.github/workflows/test-html.yml'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "NODE_VERSION=$(cat '.nvmrc')" >> ${GITHUB_ENV}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: bundle exec rake site:build
  test:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun
