name: web hosting ftp deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
      - name: install
        run: gem install bundler && bundle
      - name: build
        run: bundle exec rake site:build
      - name: test
        run: bundle exec rake site:test
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: dh.hosting.nyu.edu
          username: ${{secrets.FTP_USERNAME}}@dh.hosting.nyu.edu
          password: ${{secrets.FTP_PASSWORD}}
          state-name: ./.ftp-deploy-sync-state.json
          local-dir: ./_site/
